# Generated by Django 3.2.23 on 2024-05-29 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='padi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('varietas', models.CharField(choices=[(5, 'Pandan_Wangi'), (3, 'Ciheran'), (4, 'Mi_Kongga'), (2, 'IR64'), (1, 'Beras_Merah'), (0, 'Beras_Hitam')], max_length=100)),
                ('warna', models.CharField(choices=[(2, 'Merah'), (3, 'Putih'), (1, 'Hitam'), (0, 'Coklat')], max_length=100)),
                ('rasa', models.CharField(choices=[(0, 'Pulen'), (1, 'Sangat_Pulen')], max_length=100)),
                ('teknik', models.CharField(choices=[(1, 'SRI'), (0, 'Jajar_Legowo')], max_length=100)),
                ('musim', models.CharField(choices=[(0, 'Hujan'), (1, 'Kemarau')], max_length=100)),
                ('penyakit', models.CharField(choices=[(0, 'Burung'), (1, 'Penggerek_Batang'), (3, 'Wereng_Coklat'), (4, 'Wereng_Hijau'), (2, 'Tikus')], max_length=100)),
                ('ph', models.FloatField(validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(5.0)])),
                ('boron', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('fosfor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('grade_mutu', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
