# Generated by Django 3.2.23 on 2024-05-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readcsv', '0002_auto_20240530_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padi',
            name='grade_mutu',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
