# Generated by Django 3.2.23 on 2024-05-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readcsv', '0005_alter_padi_grade_mutu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padi',
            name='boron',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='padi',
            name='fosfor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='padi',
            name='musim',
            field=models.PositiveIntegerField(choices=[(0, 'Hujan'), (1, 'Kemarau')], null=True),
        ),
        migrations.AlterField(
            model_name='padi',
            name='penyakit',
            field=models.PositiveIntegerField(choices=[(0, 'Burung'), (1, 'Penggerek_Batang'), (3, 'Wereng_Coklat'), (4, 'Wereng_Hijau'), (2, 'Tikus')], null=True),
        ),
        migrations.AlterField(
            model_name='padi',
            name='ph',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='padi',
            name='rasa',
            field=models.PositiveIntegerField(choices=[(0, 'Pulen'), (1, 'Sangat_Pulen')], null=True),
        ),
        migrations.AlterField(
            model_name='padi',
            name='teknik',
            field=models.PositiveIntegerField(choices=[(1, 'SRI'), (0, 'Jajar_Legowo')], null=True),
        ),
        migrations.AlterField(
            model_name='padi',
            name='varietas',
            field=models.PositiveIntegerField(choices=[(5, 'Pandan_Wangi'), (3, 'Ciheran'), (4, 'Mi_Kongga'), (2, 'IR64'), (1, 'Beras_Merah'), (0, 'Beras_Hitam')], null=True),
        ),
        migrations.AlterField(
            model_name='padi',
            name='warna',
            field=models.PositiveIntegerField(choices=[(2, 'Merah'), (3, 'Putih'), (1, 'Hitam'), (0, 'Coklat')], null=True),
        ),
    ]
