# Generated by Django 3.2.23 on 2024-05-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readcsv', '0006_auto_20240530_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padi',
            name='grade_mutu',
            field=models.FloatField(blank=True),
        ),
    ]
